name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: komeo-mqtt

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - platform: linux/amd64
            target: x86_64-unknown-linux-musl
            tag_suffix: linux-amd64
          - platform: linux/arm64
            target: aarch64-unknown-linux-musl
            tag_suffix: linux-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image for ${{ matrix.platform }}
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: ${{ matrix.platform }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.tag_suffix }}
        build-args: |
          TARGET=${{ matrix.target }}

  manifest:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create and push multi-arch manifest (latest tag)
      run: |
        docker buildx imagetools create \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:linux-amd64 \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:linux-arm64
