name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: komeo-mqtt

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - platform: linux/amd64
            target: x86_64-unknown-linux-musl
          - platform: linux/arm64
            target: aarch64-unknown-linux-musl

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust with targets
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross for cross-compilation
      run: cargo install cross

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare Docker tag (replace / with - in platform)
      id: prepare_tag
      run: |
        TAG=${{ matrix.platform }}
        TAG="${TAG//\//-}"
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ matrix.platform }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        build-args: |
          TARGET=${{ matrix.target }}
